version: '3.3'

volumes:
  pg_data:
  media:
  static:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: sokolovk055/foodgram_backend
    env_file: .env
    volumes:
      - media:/app/media/recipes/
      - static:/app/backend_static/
  frontend:
    image: sokolovk055/foodgram_frontend
    env_file: .env
    volumes:
      - ../frontend/:/app/result_build/

  nginx:
    image: nginx:1.19.3
    ports:
      - "7000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - media:/media/recipes/
      - static:/staticfiles/backend_static/
