# Generated by Django 4.2.3 on 2023-08-04 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_rename_tag_recipe_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default=1, upload_to='recipes/', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
