# Generated by Django 4.2.3 on 2023-08-11 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_tagrecipe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ('id',), 'verbose_name': 'Рецепт', 'verbose_name_plural': 'Рецепты'},
        ),
    ]
